import { Provider, Car } from './types'

export const providers: Provider[] = [
  {
    id: '4hire',
    name: '4 HIRE',
    tagline: 'No Deposit Deals',
    promoTitle: '4 HIRE Special Offers',
    promoText: 'No-deposit rentals on selected sports cars and SUVs. Fast WhatsApp booking, same-day delivery available across Dubai.',
    featured: true,
    color: 'amber',
  },
  {
    id: 'habibcar',
    name: 'HABIB CAR',
    tagline: 'Best Daily Prices',
    promoTitle: 'HABIB CAR Daily Deals',
    promoText: 'Dubai\'s most affordable daily rental rates. Economy to mid-range fleet, fully insured, with flexible pickup locations.',
    featured: true,
    color: 'emerald',
  },
  {
    id: 'exoticcar',
    name: 'EXOTIC CAR',
    tagline: 'Luxury Fleet',
    promoTitle: 'EXOTIC CAR Collection',
    promoText: 'Lamborghini, Ferrari, Mercedes AMG and more. Exclusive weekly packages and VIP concierge delivery to your door.',
    featured: true,
    color: 'violet',
  },
  {
    id: 'royaldrive',
    name: 'ROYAL DRIVE',
    tagline: 'Sports & SUV',
    promoTitle: 'ROYAL DRIVE Exclusives',
    promoText: 'Performance sports cars and premium SUVs. Special weekend rates and monthly packages for long-term renters.',
    featured: false,
    color: 'blue',
  },
  {
    id: 'elitedrive',
    name: 'ELITE DRIVE',
    tagline: 'Premium Collection',
    promoTitle: 'ELITE DRIVE Premium',
    promoText: 'Curated premium fleet for business and leisure. Full insurance, 24/7 roadside assistance, and door-to-door service.',
    featured: false,
    color: 'rose',
  },
]

export const cars: Car[] = [
  // ── 4 HIRE ─────────────────────────────────
  {
    id: 'mustang-2024',
    providerId: '4hire',
    providerName: '4 HIRE',
    brand: 'Ford',
    model: 'Mustang GT',
    year: 2024,
    category: 'Sports',
    dailyPrice: 350,
    weeklyPrice: 2100,
    monthlyPrice: 7500,
    depositType: 'no-deposit',
    availableNow: true,
    transmission: 'Automatic',
    seats: 4,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=800&q=80',
    isHotDeal: true,
    isPopular: true,
    isNewArrival: false,
    shortDescription: 'The iconic American muscle car in its latest form. V8 power, Fastback styling, and zero deposit required. A true head-turner on Dubai roads.',
    highlights: ['Zero deposit required', 'V8 5.0L 450hp engine', 'Same-day delivery available'],
    rating: 4.9,
    reviewCount: 147,
    features: ['V8 5.0L Engine', 'Fastback Body', 'Apple CarPlay', 'Rear Camera', 'Keyless Entry', 'Premium Audio'],
  },
  {
    id: 'camaro-2024',
    providerId: '4hire',
    providerName: '4 HIRE',
    brand: 'Chevrolet',
    model: 'Camaro SS',
    year: 2024,
    category: 'Sports',
    dailyPrice: 380,
    weeklyPrice: 2280,
    monthlyPrice: 8200,
    depositType: 'no-deposit',
    availableNow: true,
    transmission: 'Automatic',
    seats: 4,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: false,
    isNewArrival: true,
    shortDescription: 'Bold muscle with SS performance package. Wide body, V8 rumble, and a commanding presence on Dubai roads — and no deposit needed.',
    highlights: ['No deposit required', 'V8 6.2L 455hp', 'Brembo brakes included'],
    rating: 4.8,
    reviewCount: 89,
    features: ['V8 6.2L Engine', 'SS Performance Pack', 'Brembo Brakes', 'Head-Up Display', 'Wireless CarPlay', 'Sport Exhaust'],
  },
  // ── HABIB CAR ─────────────────────────────────
  {
    id: 'mustang-2023',
    providerId: 'habibcar',
    providerName: 'HABIB CAR',
    brand: 'Ford',
    model: 'Mustang EcoBoost',
    year: 2023,
    category: 'Sports',
    dailyPrice: 280,
    weeklyPrice: 1680,
    monthlyPrice: 5900,
    depositType: 'no-deposit',
    availableNow: true,
    transmission: 'Automatic',
    seats: 4,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: true,
    isNewArrival: false,
    shortDescription: 'Sporty performance at an accessible daily rate. EcoBoost turbocharged engine with full modern tech and no deposit required.',
    highlights: ['No deposit required', 'AED 280/day only', 'EcoBoost turbo engine'],
    rating: 4.7,
    reviewCount: 203,
    features: ['EcoBoost 2.3L Turbo', 'Sport Mode', 'Apple CarPlay', 'Android Auto', 'Rear Camera', 'Lane Assist'],
  },
  {
    id: 'landcruiser-2023',
    providerId: 'habibcar',
    providerName: 'HABIB CAR',
    brand: 'Toyota',
    model: 'Land Cruiser VX',
    year: 2023,
    category: 'SUV',
    dailyPrice: 400,
    weeklyPrice: 2400,
    monthlyPrice: 8500,
    depositType: 'no-deposit',
    availableNow: true,
    transmission: 'Automatic',
    seats: 7,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: true,
    isNewArrival: false,
    shortDescription: 'The undisputed king of UAE roads. 7-seater VX trim, no-deposit offer, with legendary reliability and commanding off-road performance.',
    highlights: ['7-seater VX trim', 'No deposit required', 'Off-road ready'],
    rating: 4.9,
    reviewCount: 311,
    features: ['V6 3.5L Twin-Turbo', '7-Seater', 'Multi-Terrain Select', 'E-KDSS Suspension', 'JBL Premium Audio', 'Triple Zone AC'],
  },
  {
    id: 'jeep-wrangler-2023',
    providerId: 'habibcar',
    providerName: 'HABIB CAR',
    brand: 'Jeep',
    model: 'Wrangler Sahara',
    year: 2023,
    category: 'SUV',
    dailyPrice: 280,
    weeklyPrice: 1680,
    monthlyPrice: 5800,
    depositType: 'no-deposit',
    availableNow: true,
    transmission: 'Automatic',
    seats: 5,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=80',
    isHotDeal: true,
    isPopular: true,
    isNewArrival: false,
    shortDescription: 'The ultimate adventure SUV at the best daily rate in Dubai. Removable roof, trail-rated 4WD, no deposit needed.',
    highlights: ['Removable roof & doors', 'Trail-rated 4WD', 'No deposit required'],
    rating: 4.8,
    reviewCount: 176,
    features: ['2.0L Turbo Petrol', 'Trail-Rated 4x4', 'Removable Soft Top', 'Apple CarPlay', 'Skid Plates', 'Off-Road Tires'],
  },
  {
    id: 'camry-2024',
    providerId: 'habibcar',
    providerName: 'HABIB CAR',
    brand: 'Toyota',
    model: 'Camry Grande',
    year: 2024,
    category: 'Economy',
    dailyPrice: 150,
    weeklyPrice: 900,
    monthlyPrice: 3200,
    depositType: 'no-deposit',
    availableNow: true,
    transmission: 'Automatic',
    seats: 5,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: true,
    isNewArrival: false,
    shortDescription: 'Dubai\'s most practical daily driver. Comfortable, fuel-efficient, and incredibly affordable — perfect for business trips or extended stays.',
    highlights: ['Best value in Dubai', 'Full insurance included', 'No deposit required'],
    rating: 4.6,
    reviewCount: 428,
    features: ['2.5L Petrol', 'Leather Seats', 'Apple CarPlay', 'Adaptive Cruise', 'Dual-Zone AC', 'Parking Sensors'],
  },
  {
    id: 'mercedes-c300-2024',
    providerId: 'habibcar',
    providerName: 'HABIB CAR',
    brand: 'Mercedes-Benz',
    model: 'C300 AMG Line',
    year: 2024,
    category: 'Luxury',
    dailyPrice: 250,
    weeklyPrice: 1500,
    monthlyPrice: 5200,
    depositType: 'no-deposit',
    availableNow: true,
    transmission: 'Automatic',
    seats: 5,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: false,
    isNewArrival: true,
    shortDescription: 'Entry to the Mercedes luxury world at an unbeatable price. AMG Line package, MBUX system, and premium interior at just AED 250/day.',
    highlights: ['AMG Line package', 'MBUX infotainment', 'No deposit required'],
    rating: 4.7,
    reviewCount: 134,
    features: ['2.0L Turbocharged', 'AMG Line Package', 'MBUX Display', 'Burmester Sound', 'Digital Cockpit', 'Heated Seats'],
  },
  // ── EXOTIC CAR ─────────────────────────────────
  {
    id: 'g63-2023',
    providerId: 'exoticcar',
    providerName: 'EXOTIC CAR',
    brand: 'Mercedes-Benz',
    model: 'G 63 AMG',
    year: 2023,
    category: 'Luxury',
    dailyPrice: 1200,
    weeklyPrice: 7200,
    monthlyPrice: 24000,
    depositType: 'deposit',
    depositAmount: 5000,
    availableNow: true,
    transmission: 'Automatic',
    seats: 5,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1563720223809-b2d1abf4e3ad?auto=format&fit=crop&w=800&q=80',
    isHotDeal: true,
    isPopular: true,
    isNewArrival: false,
    shortDescription: 'The legendary G-Wagon AMG. 585hp Biturbo V8, iconic box-body design, supreme off-road capability, and unmatched street presence in Dubai.',
    highlights: ['AMG V8 Biturbo 585hp', 'VIP concierge delivery', 'Designo interior'],
    rating: 5.0,
    reviewCount: 98,
    features: ['AMG V8 Biturbo 585hp', 'Designo Interior', 'Burmester Sound', 'AMG Ride Control', 'Night Package', 'Panoramic Roof', 'Heated Seats'],
  },
  {
    id: 'urus-2024',
    providerId: 'exoticcar',
    providerName: 'EXOTIC CAR',
    brand: 'Lamborghini',
    model: 'Urus S',
    year: 2024,
    category: 'Exotic',
    dailyPrice: 2500,
    weeklyPrice: 15000,
    monthlyPrice: 50000,
    depositType: 'deposit',
    depositAmount: 10000,
    availableNow: true,
    transmission: 'Automatic',
    seats: 5,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: true,
    isNewArrival: true,
    shortDescription: 'The world\'s most exciting SUV. 666hp twin-turbo V8, Lamborghini DNA in a practical form, for those who demand the extraordinary.',
    highlights: ['V8 Twin-Turbo 666hp', 'Lamborghini heritage', 'VIP door delivery'],
    rating: 5.0,
    reviewCount: 67,
    features: ['V8 Twin-Turbo 666hp', 'ANIMA Drive Modes', 'Carbon Ceramic Brakes', '23" Forged Wheels', 'Alcantara Interior', 'B&O Sound'],
  },
  {
    id: 'ferrari-roma-2024',
    providerId: 'exoticcar',
    providerName: 'EXOTIC CAR',
    brand: 'Ferrari',
    model: 'Roma',
    year: 2024,
    category: 'Exotic',
    dailyPrice: 3500,
    weeklyPrice: 21000,
    monthlyPrice: 70000,
    depositType: 'deposit',
    depositAmount: 15000,
    availableNow: true,
    transmission: 'Automatic',
    seats: 2,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1544544784-f748eed3a2e4?auto=format&fit=crop&w=800&q=80',
    isHotDeal: true,
    isPopular: false,
    isNewArrival: false,
    shortDescription: 'La Dolce Vita redefined. The Ferrari Roma is a tour de force of Italian design and V8 performance — the ultimate Dubai statement.',
    highlights: ['V8 Turbo 620hp', 'Prancing horse prestige', 'Roma cockpit design'],
    rating: 4.9,
    reviewCount: 44,
    features: ['V8 620hp', 'Maranello DNA', 'Roma Cockpit', 'Ferrari Dynamic Enhancer', 'Carbon Fibre Pack', 'Racing Seats'],
  },
  {
    id: 'rolls-ghost-2023',
    providerId: 'exoticcar',
    providerName: 'EXOTIC CAR',
    brand: 'Rolls-Royce',
    model: 'Ghost',
    year: 2023,
    category: 'Exotic',
    dailyPrice: 3000,
    weeklyPrice: 18000,
    monthlyPrice: 60000,
    depositType: 'deposit',
    depositAmount: 12000,
    availableNow: true,
    transmission: 'Automatic',
    seats: 5,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: true,
    isNewArrival: false,
    shortDescription: 'The pinnacle of automotive luxury. The Rolls-Royce Ghost delivers a whisper-quiet, effortlessly powerful experience unlike any other vehicle on earth.',
    highlights: ['6.75L V12 571hp', 'Magic Carpet Ride', 'Starlight headliner'],
    rating: 5.0,
    reviewCount: 29,
    features: ['V12 6.75L Twin-Turbo', 'Starlight Headliner', 'Bespoke Audio', 'Rear Theatre Config', 'Champagne Cooler', 'Lambswool Mats'],
  },
  // ── ROYAL DRIVE ─────────────────────────────────
  {
    id: 'camaro-2023',
    providerId: 'royaldrive',
    providerName: 'ROYAL DRIVE',
    brand: 'Chevrolet',
    model: 'Camaro LT1',
    year: 2023,
    category: 'Sports',
    dailyPrice: 320,
    weeklyPrice: 1920,
    monthlyPrice: 6800,
    depositType: 'deposit',
    depositAmount: 1500,
    availableNow: true,
    transmission: 'Automatic',
    seats: 4,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?auto=format&fit=crop&w=800&q=80',
    isHotDeal: true,
    isPopular: false,
    isNewArrival: false,
    shortDescription: 'Track-ready performance for the road. Aggressive styling with the LT1 V8 making every drive extraordinary.',
    highlights: ['LT1 V8 455hp', 'Magnetic Ride Control', 'Launch Control system'],
    rating: 4.8,
    reviewCount: 112,
    features: ['V8 LT1 Engine', 'Magnetic Ride Control', 'Launch Control', 'Dual-Zone AC', 'Leather Seats', 'Bose Audio'],
  },
  {
    id: 'patrol-2023',
    providerId: 'royaldrive',
    providerName: 'ROYAL DRIVE',
    brand: 'Nissan',
    model: 'Patrol Platinum',
    year: 2023,
    category: 'SUV',
    dailyPrice: 450,
    weeklyPrice: 2700,
    monthlyPrice: 9500,
    depositType: 'deposit',
    depositAmount: 2000,
    availableNow: true,
    transmission: 'Automatic',
    seats: 8,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: true,
    isNewArrival: false,
    shortDescription: 'The ultimate Dubai SUV. 8-seat platinum trim with V8 power, perfect for family trips or group travel across the UAE.',
    highlights: ['8-seater Platinum trim', 'V8 5.6L 400hp', 'Full UAE road presence'],
    rating: 4.9,
    reviewCount: 267,
    features: ['V8 5.6L Engine', '8-Seater', 'Platinum Interior', '4WD System', 'Triple Zone AC', 'Captain Seats', 'Sunroof'],
  },
  {
    id: 'cayenne-2024',
    providerId: 'royaldrive',
    providerName: 'ROYAL DRIVE',
    brand: 'Porsche',
    model: 'Cayenne S',
    year: 2024,
    category: 'SUV',
    dailyPrice: 850,
    weeklyPrice: 5100,
    monthlyPrice: 18000,
    depositType: 'deposit',
    depositAmount: 3500,
    availableNow: false,
    transmission: 'Automatic',
    seats: 5,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1580274455191-1c62238fa333?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: false,
    isNewArrival: true,
    shortDescription: 'Sports car performance in SUV clothing. The Cayenne S delivers a driving experience no other SUV can match — arriving soon.',
    highlights: ['V6 Biturbo 434hp', 'PASM Sport Suspension', 'Sport Chrono package'],
    rating: 4.8,
    reviewCount: 58,
    features: ['V6 2.9L Biturbo', 'PASM Sport Suspension', 'Air Suspension', 'Bose Surround', 'Sport Chrono Package', '21" Turbo Wheels'],
  },
  {
    id: 'porsche-911-2024',
    providerId: 'royaldrive',
    providerName: 'ROYAL DRIVE',
    brand: 'Porsche',
    model: '911 Carrera',
    year: 2024,
    category: 'Sports',
    dailyPrice: 950,
    weeklyPrice: 5700,
    monthlyPrice: 20000,
    depositType: 'deposit',
    depositAmount: 4000,
    availableNow: true,
    transmission: 'Automatic',
    seats: 2,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: true,
    isNewArrival: true,
    shortDescription: 'The purest sports car experience. 70 years of Porsche engineering perfected — the 911 remains the benchmark for driving pleasure.',
    highlights: ['Flat-6 385hp engine', 'Porsche heritage icon', '0-100 in 4.2 seconds'],
    rating: 4.9,
    reviewCount: 73,
    features: ['Flat-6 3.0L Twin-Turbo', 'Sport Exhaust', 'PASM Chassis', 'PCM Infotainment', 'Sport Seats Plus', 'LED Matrix Lights'],
  },
  {
    id: 'dodge-charger-2023',
    providerId: 'royaldrive',
    providerName: 'ROYAL DRIVE',
    brand: 'Dodge',
    model: 'Charger RT',
    year: 2023,
    category: 'Sports',
    dailyPrice: 280,
    weeklyPrice: 1680,
    monthlyPrice: 5800,
    depositType: 'deposit',
    depositAmount: 1500,
    availableNow: true,
    transmission: 'Automatic',
    seats: 5,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1612544448445-b8232cff3b6c?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: false,
    isNewArrival: false,
    shortDescription: 'American muscle, four-door practicality. The Charger RT delivers V8 thunder for five passengers — the only muscle car you can share.',
    highlights: ['V8 HEMI 370hp', '5-door muscle car', 'SRT styling package'],
    rating: 4.6,
    reviewCount: 92,
    features: ['V8 5.7L HEMI', 'SRT Styling Pack', 'Performance Exhaust', 'UConnect Display', 'Leather Interior', 'Dodge Safety Group'],
  },
  // ── ELITE DRIVE ─────────────────────────────────
  {
    id: 'bmw7-2024',
    providerId: 'elitedrive',
    providerName: 'ELITE DRIVE',
    brand: 'BMW',
    model: '7 Series 760i',
    year: 2024,
    category: 'Luxury',
    dailyPrice: 700,
    weeklyPrice: 4200,
    monthlyPrice: 15000,
    depositType: 'deposit',
    depositAmount: 3000,
    availableNow: true,
    transmission: 'Automatic',
    seats: 5,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: false,
    isNewArrival: true,
    shortDescription: 'BMW\'s flagship redefined. Theatre Screen, Executive Lounge seating, and V12 performance for the ultimate business class experience.',
    highlights: ['V12 engine', 'Theatre Screen inside', '24/7 door-to-door service'],
    rating: 4.8,
    reviewCount: 81,
    features: ['V12 Engine', 'Theatre Screen', 'Executive Lounge', 'Crystal Headlights', 'Massage Seats', 'Bowers & Wilkins Audio', 'Rear Entertainment'],
  },
  {
    id: 'rrsport-2024',
    providerId: 'elitedrive',
    providerName: 'ELITE DRIVE',
    brand: 'Range Rover',
    model: 'Sport HSE',
    year: 2024,
    category: 'SUV',
    dailyPrice: 900,
    weeklyPrice: 5400,
    monthlyPrice: 19000,
    depositType: 'deposit',
    depositAmount: 4000,
    availableNow: true,
    transmission: 'Automatic',
    seats: 5,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1616788494707-ec28f08d05a1?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: false,
    isNewArrival: true,
    shortDescription: 'Effortless sophistication in an SUV. New curved dashboard, Digital Air Suspension, and impeccable British refinement.',
    highlights: ['Digital Air Suspension', 'Curved panoramic dash', '24/7 Elite concierge'],
    rating: 4.8,
    reviewCount: 96,
    features: ['3.0L Inline-6 Turbo', 'Digital Air Suspension', 'Meridian Sound', 'Curved Dash Display', 'Heated & Cooled Seats', 'Terrain Response 2'],
  },
  {
    id: 'bmw-m4-2024',
    providerId: 'elitedrive',
    providerName: 'ELITE DRIVE',
    brand: 'BMW',
    model: 'M4 Competition',
    year: 2024,
    category: 'Sports',
    dailyPrice: 750,
    weeklyPrice: 4500,
    monthlyPrice: 16000,
    depositType: 'deposit',
    depositAmount: 3500,
    availableNow: true,
    transmission: 'Automatic',
    seats: 4,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=800&q=80',
    isHotDeal: false,
    isPopular: true,
    isNewArrival: false,
    shortDescription: 'The M4 Competition is BMW at its most extreme. 510hp inline-6 twin-turbo, M-specific chassis, and electrifying performance in every gear.',
    highlights: ['S58 Twin-Turbo 510hp', 'M xDrive all-wheel drive', '0-100 in 3.5 seconds'],
    rating: 4.9,
    reviewCount: 119,
    features: ['S58 3.0L Twin-Turbo 510hp', 'M xDrive AWD', 'M Carbon Seats', 'M Compound Brakes', 'Adaptive M Suspension', 'Active M Differential'],
  },
  {
    id: 'audi-q8-2024',
    providerId: 'elitedrive',
    providerName: 'ELITE DRIVE',
    brand: 'Audi',
    model: 'Q8 S Line',
    year: 2024,
    category: 'SUV',
    dailyPrice: 650,
    weeklyPrice: 3900,
    monthlyPrice: 14000,
    depositType: 'deposit',
    depositAmount: 3000,
    availableNow: true,
    transmission: 'Automatic',
    seats: 5,
    fuelType: 'Petrol',
    image: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=800&q=80',
    isHotDeal: true,
    isPopular: true,
    isNewArrival: false,
    shortDescription: 'Audi\'s luxury SUV coupé with quattro performance and S Line sport package. The Q8 combines spectacular design with confident all-road capability.',
    highlights: ['Quattro all-wheel drive', 'S Line sport package', 'Virtual Cockpit Plus'],
    rating: 4.8,
    reviewCount: 138,
    features: ['3.0L V6 TFSI 340hp', 'quattro AWD', 'S Line Package', 'Virtual Cockpit Plus', 'Bang & Olufsen Sound', 'Air Suspension'],
  },
]

export const getCarById = (id: string): Car | undefined =>
  cars.find((car) => car.id === id)

export const getCarsByProvider = (providerId: string): Car[] =>
  cars.filter((car) => car.providerId === providerId)

export const getHotDeals = (): Car[] =>
  cars.filter((car) => car.isHotDeal)

export const getPopularCars = (): Car[] =>
  cars.filter((car) => car.isPopular)

export const getNewArrivals = (): Car[] =>
  cars.filter((car) => car.isNewArrival)

export const getProviderById = (id: string): Provider | undefined =>
  providers.find((p) => p.id === id)

export const getFeaturedCar = (): Car =>
  cars.filter((c) => c.isHotDeal && c.rating >= 4.9)[0] || cars[0]
